<x-admin-layout>
    <x-slot name="title">Manage Criteria</x-slot>
    <x-slot name="header"><div class="flex items-center gap-2 text-[10px] font-mono text-text-secondary uppercase tracking-widest"><a href="{{ route('dashboard') }}" class="hover:text-accent">DASHBOARD</a><span>/</span><a href="{{ route('contests.exposures', $exposure->contest_id) }}" class="hover:text-accent">EXPOSURES</a><span>/</span><span class="text-text-primary">{{ strtoupper($exposure->name) }}</span><span>/</span><span class="text-text-primary">CRITERIA</span></div></x-slot>

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div class="lg:col-span-2"><div class="flex justify-between items-end mb-8"><div><h2 class="text-4xl mb-1">MANAGE CRITERIA</h2><p class="text-text-secondary font-mono text-[10px] uppercase tracking-widest">Build the scoring formula for {{ $exposure->name }}.</p></div><button type="button" id="add-criterion-button" class="tactical-button">+ ADD CRITERION</button></div>
        @if(session('success'))<div class="mb-6 border-l-2 border-success bg-success/5 px-5 py-4 text-[10px] font-mono uppercase tracking-widest text-success">{{ session('success') }}</div>@endif
        <div class="space-y-4">
            @forelse($criteria as $index => $item)
                <details class="tactical-card group border-l-2 border-border open:border-accent"><summary class="flex cursor-pointer list-none items-center gap-5 p-5"><span class="text-lg font-mono text-accent">{{ sprintf('%02d', $index + 1) }}</span><div class="flex-1"><h3 class="text-lg tracking-wide text-white">{{ $item->name }}</h3><p class="mt-1 text-[9px] font-mono uppercase tracking-widest text-text-secondary">{{ $item->percentage }}% of the formula</p></div><span class="text-[9px] font-mono uppercase text-accent">EDIT</span></summary><div class="border-t border-border p-5"><form action="{{ route('criteria.update', $item) }}" method="POST" class="grid grid-cols-1 md:grid-cols-3 gap-4">@csrf @method('PATCH')<div class="md:col-span-2"><label class="mb-2 block text-[9px] font-mono uppercase text-text-secondary">Criterion name</label><input name="name" value="{{ $item->name }}" required class="w-full border border-border bg-background-primary px-3 py-2 font-mono text-sm text-white"></div><div><label class="mb-2 block text-[9px] font-mono uppercase text-text-secondary">Weight %</label><input type="number" name="percentage" min="0" max="100" step="0.01" value="{{ $item->percentage }}" required class="w-full border border-border bg-background-primary px-3 py-2 font-mono text-sm text-white"></div><div class="md:col-span-3 flex justify-end gap-3"><button class="border border-accent px-4 py-2 text-[9px] font-mono uppercase text-accent hover:bg-accent hover:text-white">SAVE CHANGES</button></form><form action="{{ route('criteria.destroy', $item) }}" method="POST">@csrf @method('DELETE')<button onclick="return confirm('Remove this criterion?')" class="border border-danger px-4 py-2 text-[9px] font-mono uppercase text-danger hover:bg-danger hover:text-white">REMOVE</button></form></div></div></details>
            @empty <div class="tactical-card p-12 text-center text-[10px] font-mono uppercase tracking-widest text-text-secondary">No criteria yet. Add the first item to build your formula.</div>
            @endforelse
        </div></div>

        <aside class="space-y-6"><div class="tactical-card p-6 border-t-2 border-accent"><h3 class="text-lg mb-5">LIVE FORMULA</h3><div class="rounded border border-border bg-background-primary p-4 font-mono text-[11px] leading-loose text-text-secondary">@forelse($criteria as $item)<div><span class="text-white">{{ $item->name }}</span> <span class="text-accent">({{ $item->percentage }}%)</span>{{ ! $loop->last ? ' +' : '' }}</div>@empty<span>Add criteria to create a formula.</span>@endforelse</div><div class="mt-5 flex justify-between border-t border-border pt-4 text-[10px] font-mono uppercase"><span class="text-text-secondary">Total weight</span><span class="{{ $criteria->sum('percentage') == 100 ? 'text-success' : 'text-danger' }}">{{ $criteria->sum('percentage') }}%</span></div><div class="mt-3 flex justify-between text-[9px] font-mono uppercase"><span class="text-text-secondary">Remaining</span><span class="text-accent">{{ 100 - $criteria->sum('percentage') }}%</span></div><p class="mt-4 text-[9px] font-mono leading-relaxed text-text-secondary">Set each criterion’s percentage until the formula reaches exactly 100%. The formula uses these weights.</p></div></aside>
    </div>

    <div id="criterion-modal" class="{{ $errors->any() ? '' : 'hidden' }} fixed inset-0 z-[1100] flex items-center justify-center bg-black/80 p-4"><div class="w-full max-w-lg tactical-card border border-accent bg-background-secondary p-8 shadow-2xl"><div class="mb-6 flex justify-between"><div><div class="text-[9px] font-mono uppercase tracking-[0.3em] text-accent">Formula item</div><h3 class="mt-2 text-2xl tracking-widest text-white">ADD CRITERION</h3></div><button type="button" data-close-criterion-modal class="text-xl text-text-secondary">&times;</button></div><form action="{{ route('criteria.store', $exposure) }}" method="POST" class="space-y-5">@csrf<div><label class="mb-2 block text-[9px] font-mono uppercase text-text-secondary">Criterion name</label><input name="name" value="{{ old('name') }}" required class="w-full border border-border bg-background-primary px-4 py-3 font-mono text-white">@error('name')<p class="mt-1 text-[9px] text-danger">{{ $message }}</p>@enderror</div><div><label class="mb-2 block text-[9px] font-mono uppercase text-text-secondary">Weight %</label><input type="number" min="0" max="100" step="0.01" name="percentage" value="{{ old('percentage') }}" required class="w-full border border-border bg-background-primary px-3 py-3 font-mono text-white">@error('percentage')<p class="mt-1 text-[9px] text-danger">{{ $message }}</p>@enderror</div><div class="flex justify-end gap-3"><button type="button" data-close-criterion-modal class="px-4 py-3 text-[10px] font-mono uppercase text-text-secondary">Cancel</button><button class="tactical-button">ADD TO FORMULA</button></div></form></div></div>
    @push('scripts')<script>document.addEventListener('DOMContentLoaded', () => { const modal = document.getElementById('criterion-modal'); document.getElementById('add-criterion-button')?.addEventListener('click', () => modal.classList.remove('hidden')); modal?.querySelectorAll('[data-close-criterion-modal]').forEach(button => button.addEventListener('click', () => modal.classList.add('hidden'))); });</script>@endpush
</x-admin-layout>
